name: flutter_genui_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter

  firebase_ai: ^3.5.0
  firebase_core: ^4.2.1
  genui_firebase_ai: ^0.5.1
  genui: ^0.5.1
  json_schema_builder: ^0.1.3
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
